### ISSUE TITLE
lookit-api builds timing out at step deploy-to-cluster

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-orchestrator#16]
The last few staging builds for lookit-api have failed due to the deploy-to-cluster step timing out. E.g. [here](https://console.cloud.google.com/cloud-build/builds;region=global/c042873b-e3d8-4711-85a6-4c11d910884a;step=7?project=mit-lookit).

* There are different amounts of progress in this step, so I'm not sure if there is something actually going wrong, or they're legitimately just taking longer than we expect them to and we should increase the time before they're considered to have timed out.

* The lookit-api cloud build process is defined at https://github.com/lookit/lookit-api/blob/master/cloudbuild.yaml

**Comment by jtrouth** [comment]
The time limit being hit is the overall 10-minute default timeout for a cloud build job. Looks like it's actually the tests in step 4 that are taking extra time and pushing the build over that limit. 

[Pull request 637](https://github.com/lookit/lookit-api/pull/637) extends the timeout on the job to 20 minutes.

**Comment by kimberscott** [comment]
Thanks so much for figuring that out - makes sense & that fixed it!
